/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.directivedsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DirectiveDSLStandaloneSetup extends DirectiveDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new DirectiveDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
