/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.directivedsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DirectiveDSLRuntimeModule extends AbstractDirectiveDSLRuntimeModule {
}
